### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by mortezakarimi** [lukaszpaczos/sails-datatable#4]
I get this errors on console when run controller action

```
error: Sending 500 ("Server Error") response: 
 TypeError: Cannot read property 'start' of undefined
    at module.exports.adapter.datatable (/var/www/nodejs/khayyam_computer/node_modules/sails-datatable/lib/adapter.js:43:25)
    at self.(anonymous function) (/var/www/nodejs/khayyam_computer/node_modules/sails/node_modules/waterline/lib/waterline/query/adapters.js:39:29)
    at wrapper [as datatable] (/var/www/nodejs/khayyam_computer/node_modules/sails/node_modules/lodash/index.js:3095:19)
    at Object.module.exports.index (/var/www/nodejs/khayyam_computer/api/controllers/Admin/NewsController.js:16:10)
    at wrapper (/var/www/nodejs/khayyam_computer/node_modules/sails/node_modules/lodash/index.js:3095:19)
    at routeTargetFnWrapper (/var/www/nodejs/khayyam_computer/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:164:37)
    at param (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:138:11)
    at param (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:135:11)
    at pass (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:167:11)
    at /var/www/nodejs/khayyam_computer/node_modules/sails/lib/router/bind.js:187:7
    at module.exports (/var/www/nodejs/khayyam_computer/api/policies/viewUtils.js:93:12)
    at routeTargetFnWrapper (/var/www/nodejs/khayyam_computer/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:164:37)
    at param (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:138:11)
    at param (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:135:11)
    at pass (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:167:11)
    at /var/www/nodejs/khayyam_computer/node_modules/sails/lib/router/bind.js:187:7
    at module.exports (/var/www/nodejs/khayyam_computer/api/policies/baseUrl.js:12:12)
    at routeTargetFnWrapper (/var/www/nodejs/khayyam_computer/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:164:37)
    at param (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:138:11)
    at param (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:135:11)
    at pass (/var/www/nodejs/khayyam_computer/node_modules/express/lib/router/index.js:145:5) [TypeError: Cannot read property 'start' of undefined]

```

my config/adapters.js file

```
module.exports.adatpters = {
    'sails-datatable': require('sails-datatable')
};
```

my config/connections.js file

```
datatable: {
        adapter: 'sails-datatable'
    },
```

my controller/admin/newsController.js file

```
module.exports = {



  /**
   * `Admin/NewsController.index()`
   */
  index: function (req, res,next) {
    News.datatable(req.body, function (err, data) {
      if (err) {
        return sails.log.error(err);
      } else {
        res.send(data);
        next();
      }
    });
  },
}
```

I use sails version 0.12.1

**Comment by lukaszpaczos** [comment]
Looks like configuration is ok. I think your problem is frontend usage of datatable. I tested datatable version 1.10.4...here is my implementation in angluar.js:

```
DTOptionsBuilder.newOptions()
            .withDataProp('data')
            .withOption('processing', true)
            .withOption('ajax', {
                url: CONFIG.host + 'articles/datatable',
                type: 'POST'
            })
            .withOption('serverSide', true)
            .withPaginationType('full_numbers')
            .withOption('language', {
                paginate: {
                    first: '«',
                    last: '»',
                    next: '→',
                    previous: '←'
                }
            });
```

You can try with this...especially with 'ajax' option (but you need to put there right url of our backend)

Best regards
